### ISSUE TITLE
Agent does not reconnect to socket

### ISSUE THREAD

**Issue by dlanderson** [scoutapp/scout_apm_node#170]
While running a node app, kill the core agent, then restart the core agent. The node app does not reconnect to the socket.

**Comment by vados-scout** [comment]
Hey @dlanderson I tried to add a test for this, but it's passing with the correct code -- I send a transaction, kill the `core-agent` child process, then restart it and send another transaction and they both make it across the wire... 

I might need more to reproduce this failure or at least to automate the conditions under which the failures were occurring -- do you by chance have any more hints? I know it was a while ago, it's been a whole 8 days before I could get down to working on this.
