### ISSUE TITLE
HTTP URL should be captured for HTTP spans

### ISSUE THREAD

**Issue by dlanderson** [scoutapp/scout_apm_node#183]
In a detailed trace in the UI, a user should be able to click the 'Details' button next to HTTP spans in order to see the URL. I believe we record this in the 'desc' tag on the span. Refer to our Python agent code for example.

<img width="1371" alt="Screenshot 2020-03-13 11 01 34" src="https://user-images.githubusercontent.com/102774/76645760-38d38800-651f-11ea-8740-6eaba02ac271.png">

**Comment by vados-scout** [comment]
Hey @dlanderson the only thing I can find for this is [the "url" tag](https://github.com/scoutapp/scout_apm_python/blob/2588b769a187c8233109f63c739af4b1ada03daa/src/scout_apm/instruments/urllib3.py#L62) which is being set right now, is that the right tag?

**Comment by dlanderson** [comment]
`url` tag looks correct - [Python Urllib instrument](https://github.com/scoutapp/scout_apm_python/blob/master/src/scout_apm/instruments/urllib3.py#L62)

I filed this issue when I noticed the test app we use didn't have the `Details` button next to it. Can you confirm it shows up in the UI when you run a test app?

**Comment by vados-scout** [comment]
Definitely will do -- hopefully in the future we'll be able [to automate even this kind of remote e2e test](https://github.com/scoutapp/scout_apm_node/issues/144) once most of the short term bugs are ironed out.

**Comment by vados-scout** [comment]
A note on the fix here -- it was a combination of changes made on the UI side (there was a minor bug), and some fixes on the agent side (the URLs were somewhat malformed/unnatural)
