### ISSUE TITLE
Scout does not monitor endpoints behind Express Router

### ISSUE THREAD

**Issue by provinceinnovation** [scoutapp/scout_apm_node#238]
When using an `express.Router()` all routes are not monitored by the server's `scout.expressMiddleware()`. Please find reproduction below.

```
const express = require('express');
const scout = require('@scout_apm/scout-apm');

const server = express();

server.use(scout.expressMiddleware());

const router = express.Router();
router.get('/', (req, res) => res.status(200).send('not monitored by scout'));

server.use('/router', router);

server.get('/', (req, res) => res.status(200).send('successfully monitored by scout'));

return scout.install({
  allowShutdown: true,
  monitor: true,
  name: 'example-app',
  key: 'examplekey',
  logFilePath: 'core-agent.log',
}, {
  logFn: console.log,
})
  .then(() => {
    console.log('installed scout apm');
    server.listen(3000, () => console.log('server started on port 3000'));
  });
```

Thanks 🙌

**Comment by provinceinnovation** [comment]
I have a feeling there will not be a clean solution to this.

**Option 1**: Try to resolve out all the paths inside the `express.Routers` from the `req.app._router.stack` array. Have looked into this a little - seems to get messy, fast!

Below is just pseudo-code for what that might look like:
```
const getRoutesOfLayer = (layer, path = '') => {
  if (layer && layer.route && layer.route.path && layer.regexp) {
    layer.route.path = path + layer.route.path;
    return [layer];
  }
  if (layer && layer.name === 'router' && layer.handle && layer.handle.stack && layer.path) {
    return layer.handle.stack.reduce((acc, routerLayer) => {
      return [
        ...acc,
        ...getRoutesOfLayer(routerLayer, path + layer.path),
      ];
    }, []);
  }
  return [];
};

matchedRouteMiddleware = req.app._router.stack
  .reduce((acc, layer) => {
    return [
      ...acc,
      ...getRoutesOfLayer(layer),
    ];
  }, [])
  .filter((middleware) => {
    // Check if the URL matches the route
    const isMatch = middleware.regexp.test(preQueryUrl);

    // Add matches in the hope that common routes will be faster than searching everything
    if (isMatch) { commonRouteMiddlewares.push(middleware); }

    return isMatch;
  })[0];
```

**Option 2:** Ditch the whole idea of express middleware and instead extend the `express.Route.prototype.dispatch` prototype.

Again, the below is just pseudo-code for what that might look like:
```
const defaultImplementation = express.Route.prototype.dispatch;
express.Route.prototype.dispatch = function handle(req, res, next) {  
  // req.route.path is now available
  handler(req, res);
  defaultImplementation.call(this, req, res, next);
};
```
^ To note - although the handler now has access to `req.route.path`, it does not include the path of the `express.Router` that it might sit under.

Not imagining this is going to be a fast fix - but keen to be kept in the loop!

**Comment by vados-scout** [comment]
Hi @provinceinnovation thanks for reporting this -- the path will be more likely the second option, with some tracking if necessary to get the routes' path if needed.

**Comment by vados-scout** [comment]
Hey @provinceinnovation so I got a chance to look at this and realized that what's happening is that the request *is* getting captured (I see requests being sent to `core-agent`) but they're not marked up with the `path` and `url` tags that they should be.

As you surmised (I think) the problem is that the URL can't be determined from the router, but the approach I'm taking is shimming the router itself (much like your second option) -- I'll be either `Router#handle` or `Router#[HTTP verb]` if I can't get everything I'd need from `handle`.
