### ISSUE TITLE
Ensure Core agent management is functionally identical to Python impl

### ISSUE THREAD

**Issue by dlanderson** [scoutapp/scout_apm_node#59]
The Node agent should be as configurable and functionally equivalent as our [Python agent](https://github.com/scoutapp/scout_apm_python/blob/master/src/scout_apm/core/core_agent_manager.py) implementation.

E.g. configurable to download different versions, from different URL, disable download, disable launching, etc.

**Comment by vados-scout** [comment]
Closing -- this was done in Dec 2019 (though there is also #68  which is new which was not being tracked by this ticket)
